// MySQL
export const ADD_MYSQL_CONNECTION = 'ADD_MYSQL_CONNECTION'
export const REMOVE_MYSQL_CONNECTION = 'REMOVE_MYSQL_CONNECTION'

// Dialogs
export const RESET_ADD_CONNECTION_DIALOG = 'RESET_ADD_CONNECTION_DIALOG'
export const TOGGLE_ADD_CONNECTION_DIALOG = 'TOGGLE_ADD_CONNECTION_DIALOG'
export const TOGGLE_LEFT_POPOVER = 'TOGGLE_LEFT_POPOVER'

// Connections
export const DELETE_CONNECTION = 'DELETE_CONNECTION'
export const INITIALIZE_CONNECTIONS = 'INITIALIZE_CONNECTIONS'
export const UPDATE_ADD_CONNECTION_FIELD = 'UPDATE_ADD_CONNECTION_FIELD'

// Postgres
export const POSTGRES_ADD_CONNECTION = 'POSTGRES_ADD_CONNECTION'
export const POSTGRES_UPDATE_TABLE_SCHEMA = 'POSTGRES_UPDATE_TABLE_SCHEMA'
export const POSTGRES_UPDATE_TABLE_DATA = 'POSTGRES_UPDATE_TABLE_DATA'
export const POSTGRES_ADD_TABLE_DATA = 'POSTGRES_ADD_TABLE_DATA '
export const POSTGRES_ADD_TABLES = 'POSTGRES_ADD_TABLES'
export const POSTGRES_DISPLAY_TABLE = 'POSTGRES_DISPLAY_TABLE'
export const POSTGRES_EXECUTE_QUERY = 'POSTGRES_EXECUTE_QUERY'
export const POSTGRES_FETCH_TABLE = 'POSTGRES_FETCH_TABLE'
export const POSTGRES_PERFORMANCE = 'POSTGRES_PERFORMANCE'
export const POSTGRES_QUERY_DATA = 'POSTGRES_QUERY_DATA'

// Main Page View
export const UPDATE_HOMEPAGE_VIEW = 'UPDATE_HOMEPAGE_VIEW'
