export const ADD_MYSQL_CONNECTION = 'ADD_MYSQL_CONNECTION'
export const REMOVE_MYSQL_CONNECTION = 'REMOVE_MYSQL_CONNECTION'


// Dialogs
export const TOGGLE_ADD_CONNECTION_DIALOG = 'TOGGLE_ADD_CONNECTION_DIALOG'
export const TOGGLE_LEFT_POPOVER = 'TOGGLE_LEFT_POPOVER'

// Connections
export const INITIALIZE_CONNECTIONS = 'INITIALIZE_CONNECTIONS'
export const UPDATE_ADD_CONNECTION_FIELD = 'UPDATE_ADD_CONNECTION_FIELD'
export const DELETE_CONNECTION = 'DELETE_CONNECTION'

// Postgres
export const POSTGRES_ADD_TABLES = 'POSTGRES_ADD_TABLES'
export const POSTGRES_EXECUTE_QUERY = 'POSTGRES_EXECUTE_QUERY'
export const POSTGRES_QUERY_DATA = 'POSTGRES_QUERY_DATA'

// Main Page View
export const UPDATE_HOMEPAGE_VIEW = 'UPDATE_HOMEPAGE_VIEW'
